name: f21zk
channels:
  - pytorch
  - conda-forge
dependencies:
  - python=3.11
  - numpy
  - pandas
  - scikit-learn
  - scipy
  - jupyterlab
  - matplotlib
  - seaborn
  - pytorch=2.4.*
  - torchvision
  - torchaudio
  - ffmpeg
  - pip
  - pip:
      - tensorflow==2.16.2