# Quadcopter + Payload Parameters
quad:
  mass: 1.5          # kg
  inertia: 0.03      # kg*m^2 (pitch inertia)
  arm_length: 0.25   # m (distance from COM to rotor)

payload:
  mass: 0.25         # kg
  rope_length: 1.0   # m (initial length)

environment:
  gravity: 9.81      # m/s^2

winch:
  model: "algebraic" # options: algebraic | first_order
  omega: 10.0        # [1/s] if first_order model used

pid:
  x:
    Kp: 8 #12 #8 
    Ki: 0
    Kd: 12 #12 #6 5
    u_min: -10 #-5.0
    u_max: 10 #5.0

  z:
    Kp: 40 #8.0
    Ki: 5 #0
    Kd: 10 #4  
    u_min: -10 #-5.0
    u_max: 10 #5.0

  theta:
    Kp: 30 
    Ki: 0
    Kd: 4 
    u_min: -10 
    u_max: 10 

  phi:
    Kp: 60 #42 #15.0
    Ki: 0.0
    Kd: 12 #10 #7.0
    u_min: -50 #-8.0
    u_max: 50 #8.0 

#These gains are for the quad only, without payload
# Uncomment to use these gains instead of the payload ones above

# pid:
#   x:
#     Kp: 8 
#     Ki: 0
#     Kd: 5
#     u_min: -5.0
#     u_max: 5.0

#   z:
#     Kp: 8.0
#     Ki: 0 
#     Kd: 4 
#     u_min: -5.0
#     u_max: 5.0

#   theta:
#     Kp: 30 
#     Kd: 4 
