seed: 0
device: "cpu"          # "cuda:0" if you have GPU

system: "pendulum"
dynamics:
  m: 0.5
  L: 0.5
  c: 0.0
  g: 9.81
  dt: 0.02
  integrator: "rk4"

data:
  n_trajectories: 1
  horizon: 200
  train_ratio: 0.8
  val_ratio: 0.1
  standardize: true

model:
  name: "mlp"
  hidden: [128, 128]
  dropout: 0.0

train:
  batch_size: 128
  epochs: 20
  lr: 1e-3
