seed: 42
device: "cpu"  # will use "cuda" if available, don't change
system: "pendulum"
dynamics:
  m: 0.5
  L: 0.5
  c: 0.0
  g: 9.81
  dt: 0.02
  integrator: "rk4"

data:
  n_trajectories: 1
  horizon: 200
  train_ratio: 0.8
  val_ratio: 0.1
  test_ratio: 0.1
  standardize: true

model:
  name: "mlp"
  in_dim: 2
  hidden: [128, 128]
  out_dim: 1
  dropout: 0.0

train:
  batch_size: 32
  epochs: 30
  lr: 1e-3
